#!/bin/bash

PM=yay

if ! uname -r ;then
    echo "Intalling linux-lts..."
    $PM -S linux-lts linux-lts-headers
else
    echo "Linux lts already installed..."
fi
$PM -S linux-firmware

# Compressors
$PM -S unzip zip tar unrar p7zip p7zip-plugins rsync

# Codecs
$PM -S a52dec faac faad2 flac jasper lame libdca libdv libmad libmpeg2 \
    libtheora libvorbis libxv wavpack x264 xvidcore libdvdcss ffmpeg \
    gstreamer gst-libav

# Fonts
$PM -S ttf-dejavu gnu-free-fonts ttf-liberation noto-fonts ttf-roboto \
    ttf-ubuntu-font-family ttf-fira-mono ttf-fira-code ttf-hack otf-hermit \
    ttc-iosevka ttf-iosevka-nerd ttf-jetbrains-mono ttf-meslo ttf-roboto-mono \
    adobe-source-code-pro-fonts ttf-fira-sans ttf-nunito adobe-source-sans-fonts \
    ttf-iosevka-term

# Apps
$PM -S powertop cups ufw obsidian fastfetch flameshot tmux neovim starship \
    btop timeshift thunar librewolf-bin podman distrobox
# gufw

powertop --auto-tune
systemctl enable cups.service
systemctl enable ufw.service
